services:
  google-meet-bot:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    # command: ["npm", "start"]
    # xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npm start
    # command: ["xvfb-run", "--auto-servernum", "--server-args='-screen 0 1280x720x24'", "npm", "start"]
    command: ["tail", "-f", "/dev/null"]
  diart-service:
    build:
      context: ./diart-service
      dockerfile: diart.Dockerfile
    ports:
      - "7007:7007"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./diart-service:/usr/src/app
      - cache:/root/.cache
    command: ["conda", "run", "--no-capture-output", "-n", "diart", "uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "7007", "--reload"]

volumes:
  cache:
